name: pyshopper
channels:
  - defaults
dependencies:
  - arviz
  - cython
  - nb_conda_kernels
  - notebook
  - numpy
  - pandas
  - pdoc3
  - pip
  - pymc3
  - requests
  - scikit-learn
  - seaborn
  - theano